### ISSUE TITLE
[Question] Works with HiFiBerry DAC+ ADC Pro?

### ISSUE THREAD

**Issue by Radiomix2000** [g4eml/Langstone#32]
Hello,
does the project work with HiFiBerry DAC+ ADC Pro ( https://thepihut.com/collections/raspberry-pi-audio-hats/products/hifiberry-dac-adc-pro )?

**Comment by g4eml** [comment]
I have no idea. If it installs as a standard Linux sound device and supports a sample rate of 48KHz then it may work. 

The project is designed to work with a low cost USB sound card and that is the only configuration that is recommended and supported. 
Other devices have been shown to work but any necessary configuration changes are down to the individual users. 

Colin G4EML. 


On 13 Oct 2020, at 18:40, Radiomix2000 <notifications@github.com> wrote:

Hello,
does the project work with HiFiBerry DAC+ ADC Pro ( https://thepihut.com/collections/raspberry-pi-audio-hats/products/hifiberry-dac-adc-pro )?
