### ISSUE TITLE
[Question] 1 or 2 antenna ? 

### ISSUE THREAD

**Issue by abarrau** [g4eml/Langstone#34]
Hello,
I am interested in your project.
But there is one thing that I cannot understand, at the exit of the pluto, there are 2 antennas (RX / TX). How do you do with this configuration ?
Do you have 1 or 2 antenna (for each band) ?
If you use only 1 antenna (on 1 band), what do you use ? 
thank you for your response,
Aurélien F4ANS

**Comment by g4eml** [comment]
Hello, 

All bands will need an external pre amplifier, power amplifier, filter and antenna relay to be usable. The relay is controlled using one of the pins of the Raspberry Pi which goes high when transmitting.
For a multi band system extra relays can be controlled using the 8 ‘band bit’ output pins. These extra relays can be used to select the correct amplifiers and antennas. 

73
Colin G4EML





On 20 Mar 2021, at 03:44, abarrau ***@***.***> wrote:

Hello,
I am interested in your project.
But there is one thing that I cannot understand, at the exit of the pluto, there are 2 antennas (RX / TX). How do you do with this configuration ?
Do you have 1 or 2 antenna (for each band) ?
If you use only 1 antenna (on 1 band), what do you use ?
thank you for your response,
Aurélien F4ANS

**Comment by abarrau** [comment]
Hi Colin, 

Ok and thank you for your answer.
I understood the use of GPIOs to change bands (with for each band, amplifier and antenna).
But I can't understand what's going on behind the amplifier, how are the RX and TX coaxial cables are connected to 1 single antenna (for 1 band).
Thanks, 73
Aurelien

**Comment by g4eml** [comment]
With a changeover relay. Operated by the transmit gpio. 



On 21 Mar 2021, at 04:01, abarrau ***@***.***> wrote:

Hi Colin,

Ok and thank you for your answer.
I understood the use of GPIOs to change bands (with for each band, amplifier and antenna).
But I can't understand what's going on behind the amplifier, how are the RX and TX coaxial cables are connected to 1 single antenna (for 1 band).
Thanks, 73
Aurelien
