### ISSUE TITLE
error after boot

### ISSUE THREAD

**Issue by wkraus** [g4eml/Langstone#43]
Got some errors at the end of the installation that I could not register. Reboot followed without problems but ended with:

cp: error writing '/dev/fb0': No space left on device

running Raspi 4 with 32 GB SSD and Bullseye software
original Raspi 7'' display
Adalm-Pluto attached but no mouse yet.

Any help ?

**Comment by g4eml** [comment]
Langstone has not been tested with the Bullseye release or using an SSD. 
As stated in the installation instructions you need to use Buster Lite. 

/dev/fb0 is the display frame buffer. It sounds like they have changed the display format when releasing Bullseye. 

Langstone will not also not work correctly without a mouse. 


Colin. 






On 17 Apr 2022, at 09:44, wkraus ***@***.***> wrote:

Got some errors at the end of the installation that I could not register. Reboot followed without problems but ended with:

cp: error writing '/dev/fb0': No space left on device

running Raspi 4 with 32 GB SSD and Bullseye software
original Raspi 7'' display
Adalm-Pluto attached but no mouse yet.

Any help ?

**Comment by wkraus** [comment]
tnx for fast response Colin.

I have installed Buster lite and Langstone seems to work, but still without Pluto and mouse.

Installation worked without any problems.

**Comment by wkraus** [comment]
After having added mouse, Pluto and USB sound card my Langstone starts without problems.
Finally, the whole installation was easy going after following all the instructions.

My AD8317 power meter shows nearly the same output as stated.

Great software  !!
